import { cookies } from 'next/headers';
import { timingSafeEqual } from 'node:crypto';
import {authDb,getSession,normalizePhone,validPassword,hashPassword,checkPassword,sessionResponse,digest,requireOrigin,OWNER_PHONE,OWNER_EMAIL} from '../../auth';
export const dynamic='force-dynamic';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function throttle(key:string,max:number){const now=Date.now();const result=await authDb().prepare('INSERT INTO auth_attempts(key,count,reset_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN auth_attempts.reset_at<=? THEN 1 ELSE auth_attempts.count+1 END,reset_at=CASE WHEN auth_attempts.reset_at<=? THEN excluded.reset_at ELSE auth_attempts.reset_at END RETURNING count').bind(await digest(key),now+15*60000,now,now).first<{count:number}>();return !!result&&result.count<=max}
export async function POST(req:Request){try{requireOrigin(req);const raw=await req.text();if(raw.length>4096)return response({error:'Request too large.'},413);const body=JSON.parse(raw);if(body.action==='logout'){const jar=await cookies();const token=jar.get('__Host-srs_session')?.value||jar.get('srs_session')?.value;if(token)await authDb().prepare('DELETE FROM auth_sessions WHERE token_hash=?').bind(await digest(token)).run();const secure=process.env.NODE_ENV==='production';return Response.json({ok:true},{headers:{'Cache-Control':'no-store','Set-Cookie':`${secure?'__Host-srs_session':'srs_session'}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${secure?'; Secure':''}`}})}
 if(body.action==='setup'){const configured=process.env.OWNER_SETUP_KEY;const given=typeof body.setupKey==='string'?body.setupKey:'';if(!configured||configured.length<24)return response({error:'Owner setup is not configured. Set OWNER_SETUP_KEY on Render.'},503);if(!await throttle('setup',10))return response({error:'Too many attempts. Try again in 15 minutes.'},429);if(Buffer.byteLength(given)!==Buffer.byteLength(configured)||!timingSafeEqual(Buffer.from(given),Buffer.from(configured)))return response({error:'Invalid setup key.'},403);if(await authDb().prepare("SELECT id FROM auth_accounts WHERE role='owner'").first())return response({error:'Owner account already exists. Use the login page.'},409);validPassword(body.password);const old=await authDb().prepare('SELECT user_id FROM ownership WHERE id=1').first<{user_id:string}>();const accountId=old?.user_id||crypto.randomUUID();const hash=await hashPassword(body.password);await authDb().batch([authDb().prepare("INSERT INTO auth_accounts(id,phone,name,role,password_hash) VALUES(?,?,?,'owner',?) ON CONFLICT(phone) DO NOTHING").bind(accountId,OWNER_PHONE,'Ajit',hash),authDb().prepare('INSERT INTO ownership(id,user_id,email) VALUES(1,?,?) ON CONFLICT(id) DO NOTHING').bind(accountId,OWNER_EMAIL)]);const row=await authDb().prepare('SELECT id,password_hash FROM auth_accounts WHERE phone=?').bind(OWNER_PHONE).first<any>();if(!row||!(await checkPassword(body.password,row.password_hash)))return response({error:'Owner account already exists. Use the login page.'},409);return sessionResponse(row.id,req)}
 if(body.action==='login'){const phone=normalizePhone(body.phone);if(typeof body.password!=='string'||body.password.length>128)return response({error:'Incorrect phone number or password.'},401);if(!await throttle('phone:'+phone,10))return response({error:'Too many login attempts. Please try again in 15 minutes.'},429);const row=await authDb().prepare('SELECT * FROM auth_accounts WHERE phone=? AND active=1').bind(phone).first<any>();const stored=row?.password_hash||'pbkdf2$100000$00000000000000000000000000000000$0000000000000000000000000000000000000000000000000000000000000000';const valid=await checkPassword(body.password,stored);if(!row||!valid)return response({error:'Incorrect phone number or password.'},401);return sessionResponse(row.id,req)}
 const actor=await getSession();if(actor?.role!=='owner')return response({error:'Owner access required.'},403);
 if(body.action==='account'){const phone=normalizePhone(body.phone);if(phone===OWNER_PHONE)return response({error:'Use owner settings to change the owner password.'},400);validPassword(body.password);if(typeof body.name!=='string'||!body.name.trim()||body.name.length>150)return response({error:'Enter the intern’s name.'},400);let row=await authDb().prepare('SELECT id,role FROM auth_accounts WHERE phone=?').bind(phone).first<any>();if(row?.role==='owner')return response({error:'Owner account cannot be changed here.'},403);const id=row?.id||crypto.randomUUID();const hash=await hashPassword(body.password);await authDb().batch([authDb().prepare("INSERT INTO auth_accounts(id,phone,name,role,password_hash,active) VALUES(?,?,?,'intern',?,1) ON CONFLICT(phone) DO UPDATE SET name=excluded.name,password_hash=excluded.password_hash,active=1").bind(id,phone,body.name.trim(),hash),authDb().prepare('DELETE FROM auth_sessions WHERE account_id=?').bind(id)]);return response({ok:true})}
 if(body.action==='active'){if(typeof body.id!=='string'||![0,1].includes(body.active))return response({error:'Invalid account.'},400);await authDb().batch([authDb().prepare("UPDATE auth_accounts SET active=? WHERE id=? AND role='intern'").bind(body.active,body.id),authDb().prepare('DELETE FROM auth_sessions WHERE account_id=? AND account_id<>?').bind(body.id,actor.userId)]);return response({ok:true})}
 if(body.action==='password'){validPassword(body.password);const account=await authDb().prepare('SELECT password_hash FROM auth_accounts WHERE id=?').bind(actor.userId).first<any>();if(typeof body.currentPassword!=='string'||body.currentPassword.length>128||!await checkPassword(body.currentPassword,account.password_hash))return response({error:'Current password is incorrect.'},400);await authDb().batch([authDb().prepare('UPDATE auth_accounts SET password_hash=? WHERE id=?').bind(await hashPassword(body.password),actor.userId),authDb().prepare('DELETE FROM auth_sessions WHERE account_id=?').bind(actor.userId)]);return sessionResponse(actor.userId,req)}return response({error:'Unknown action.'},400)
 }catch(e){if(e instanceof SyntaxError)return response({error:'Invalid request.'},400);if(e instanceof Error&&/Enter |Use a password|origin/.test(e.message))return response({error:e.message},400);console.error('Authentication operation failed');return response({error:'Sign-in is temporarily unavailable. Please try again.'},503)}}
