'use client';
import { useState,useEffect,useCallback } from 'react';
import { ClipboardList,Plus,Download,ShieldCheck,Search,Users,ArrowUpRight,Check,RefreshCw,School,FileCheck,PenLine,LogOut } from 'lucide-react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Table,TableHeader,TableHead,TableBody,TableRow,TableCell } from '@/components/ui/table';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Empty,EmptyHeader,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { Skeleton } from '@/components/ui/skeleton';
import { Toaster,toast } from 'sonner';
type RecordRow={id:string,name:string,school:string,father_phone:string,mother_phone:string,class_name:string,status:string,submitter_email:string,created_at:string};
type Member={id:string,phone:string,name:string,active:number};
const classes=['Nursery','LKG','UKG',...Array.from({length:12},(_,i)=>String(i+1)),'Other'];
const blank={id:'',name:'',school:'',fatherPhone:'',motherPhone:'',className:''};
function Choice({value,onChange,items,label}:{value:string,onChange:(s:string)=>void,items:string[],label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(x=><SelectItem key={x} value={x}>{x==='all'?label:x}</SelectItem>)}</SelectContent></Select>}
export default function Workspace({signedIn,email}:{signedIn:boolean,email:string}){
 const [data,setData]=useState<{user:{role:string},records:RecordRow[],members:Member[]}|null>(null);const [loading,setLoading]=useState(signedIn);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [tab,setTab]=useState('records');const [q,setQ]=useState('');const [cl,setCl]=useState('all');const [status,setStatus]=useState('all');const [form,setForm]=useState(blank);const [editing,setEditing]=useState(false);const [view,setView]=useState<RecordRow|null>(null);const [invite,setInvite]=useState(false);const [resetMode,setResetMode]=useState(false);const [ownerPassword,setOwnerPassword]=useState(false);const [passwords,setPasswords]=useState({currentPassword:'',password:''});const [person,setPerson]=useState({name:'',phone:'',password:''});
 const reload=useCallback(async()=>{try{const res=await fetch('/api/workspace');const d=await res.json();if(!res.ok)throw Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{if(signedIn)void reload();setForm(f=>({...f,id:f.id||crypto.randomUUID()}))},[signedIn,reload]);
 const owner=data?.user.role==='owner';const records=data?.records||[];const shown=records.filter(r=>(cl==='all'||r.class_name===cl)&&(status==='all'||r.status===status)&&[r.name,r.school,r.father_phone,r.mother_phone].some(x=>x.toLowerCase().includes(q.toLowerCase())));
 async function action(payload:object,endpoint='/api/workspace'){setBusy(true);try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await res.json();if(!res.ok)throw Error(d.error);await reload();return true}catch(e){toast.error((e as Error).message);return false}finally{setBusy(false)}}
 function newRecord(){setForm({...blank,id:crypto.randomUUID()});setEditing(false);setTab('entry')}
 function edit(r:RecordRow){setForm({id:r.id,name:r.name,school:r.school,fatherPhone:r.father_phone,motherPhone:r.mother_phone,className:r.class_name});setEditing(true);setView(null);setTab('entry')}
 async function save(e:React.FormEvent){e.preventDefault();if(!form.className){toast.error('Choose a class.');return}if(await action({action:'save',...form,id:form.id||crypto.randomUUID()})){toast.success(editing?'Record updated.':'Record submitted to the owner.');setForm({...blank,id:crypto.randomUUID()});setEditing(false);setTab('records')}}
 async function download(){setBusy(true);try{const params=new URLSearchParams({export:'csv',q,class:cl,status});const res=await fetch('/api/workspace?'+params);if(!res.ok){const d=await res.json();throw Error(d.error)}const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='student-records.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success(`${shown.length} records downloaded.`)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'filter_student_records',title:'Filter student records',description:'Filter the visible records by student name, school or parent phone. Does not modify saved data.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof (input as any).query!=='string'||(input as any).query.length>200)throw Error('query must be a string of at most 200 characters');const query=(input as any).query;setQ(query);return {query}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[]);
 return <div className="shell"><Toaster richColors position="top-right"/><header className="topbar"><a className="brand" href="/"><span className="brandmark"><ClipboardList size={23}/></span><b>SRS<span>Records</span></b></a><div className="account">{owner&&<button onClick={()=>setOwnerPassword(true)}>Password</button>}<span className="identity">{email||'Student data workspace'}{data&&<small>{owner?'Owner':data.user.role==='intern'?'Intern':'Workspace setup'}</small>}</span>{signedIn&&<button className="signout" title="Sign out" aria-label="Sign out" onClick={async()=>{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(r.ok)window.location.assign('/');else toast.error('Could not sign out. Please try again.')}}><LogOut size={18}/></button>}</div></header><main><div className="eyebrow">STUDENT DATA WORKSPACE</div><div className="titlebar"><div><h1>{owner?'Your records, organized.':data?.user.role==='intern'?'Make every entry count.':'Every record. In one place.'}</h1><p>{owner?'Review your team’s submissions and download the details you need.':'Student details and parent contacts, together in one secure workspace.'}</p></div>{data&&data.user.role!=='unconfigured'&&<button className="primary" onClick={newRecord}><Plus size={18}/> New record</button>}</div>
 {!signedIn?<section className="panel"><div className="welcome"><span className="welcomeicon"><ShieldCheck size={32}/></span><h2>A shared workspace. The right access.</h2><p>Interns enter student details. The owner sees and downloads all records.</p><a className="primary" href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT <ArrowUpRight size={17}/></a></div></section>:loading?<div className="panel loading"><Skeleton className="h-10 w-64"/><Skeleton className="h-40 w-full"/></div>:error?<section className="panel welcome" role="alert"><h2>We couldn’t load your workspace</h2><p>{error}</p><button onClick={()=>void reload()}><RefreshCw size={16}/> Try again</button></section>:data?.user.role==='unconfigured'?<section className="panel welcome"><span className="welcomeicon"><ShieldCheck size={32}/></span><h2>Set up your owner workspace</h2><p>This account will manage student records and intern access.<br/>Set up as the owner before sharing the platform with your team.</p><button className="primary" disabled={busy} onClick={()=>void action({action:'setup'})}>{busy?'Setting up…':'Create owner workspace'}</button></section>:<>
 <div className="stats"><article><span><ClipboardList size={16}/> {owner?'Total records':'My submissions'}</span><strong>{records.length}</strong><small>{owner?'Across your team':'Saved to the shared workspace'}</small></article><article><span><School size={16}/> Schools</span><strong>{new Set(records.map(r=>r.school.toLowerCase())).size}</strong><small>Represented in your records</small></article><article><span><FileCheck size={16}/> Reviewed</span><strong>{records.filter(r=>r.status==='Reviewed').length}</strong><small>{records.filter(r=>r.status==='New').length} awaiting review</small></article></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="workspace-tabs"><TabsTrigger value="records"><ClipboardList size={17}/>{owner?'All records':'My submissions'}</TabsTrigger><TabsTrigger value="entry"><PenLine size={17}/>{editing?'Edit record':'Data entry'}</TabsTrigger>{owner&&<TabsTrigger value="team"><Users size={17}/>Intern access</TabsTrigger>}</TabsList>
 <TabsContent value="records"><section className="panel"><div className="panelhead"><div><h2>{owner?'Student records':'My submissions'}</h2><p className="sub">{shown.length} {shown.length===1?'record':'records'}{q||cl!=='all'||status!=='all'?' matching your filters':''}</p></div><div className="actions"><button onClick={()=>void reload()} aria-label="Refresh records"><RefreshCw size={16}/></button>{owner&&<button disabled={busy||!shown.length} onClick={()=>void download()}><Download size={17}/> Download CSV</button>}</div></div><div className="filters"><div className="search"><Search size={18}/><input aria-label="Search records" placeholder="Search name, school or phone…" value={q} onChange={e=>setQ(e.target.value)}/></div><Choice value={cl} onChange={setCl} items={['all',...classes]} label="All classes"/><Choice value={status} onChange={setStatus} items={['all','New','Reviewed']} label="All statuses"/></div>
 {shown.length?<Table><TableHeader><TableRow><TableHead>Student / school</TableHead><TableHead>Class</TableHead><TableHead>Father’s number</TableHead><TableHead>Mother’s number</TableHead><TableHead>Status</TableHead><TableHead><span className="sr-only">Actions</span></TableHead></TableRow></TableHeader><TableBody>{shown.map(r=><TableRow key={r.id}><TableCell><button className="recordname" onClick={()=>setView(r)}>{r.name}</button><div className="schoolname">{r.school}</div></TableCell><TableCell><span className="classbadge">{r.class_name}</span></TableCell><TableCell>{r.father_phone||'—'}</TableCell><TableCell>{r.mother_phone||'—'}</TableCell><TableCell><span className={'status '+(r.status==='Reviewed'?'reviewed':'')}>{r.status==='Reviewed'&&<Check size={13}/>} {r.status}</span></TableCell><TableCell><button className="textbutton" onClick={()=>setView(r)}>View <ArrowUpRight size={15}/></button></TableCell></TableRow>)}</TableBody></Table>:<Empty className="empty-state"><EmptyHeader><span className="welcomeicon"><ClipboardList size={28}/></span><EmptyTitle>{records.length?'No matching records':'Your first record starts here'}</EmptyTitle><EmptyDescription>{records.length?'Try another name, school, class or status.':'Add a student’s details. Submissions will appear here as your team enters them.'}</EmptyDescription></EmptyHeader>{records.length?<button onClick={()=>{setQ('');setCl('all');setStatus('all')}}>Clear filters</button>:<button onClick={newRecord} className="primary"><Plus size={16}/> Add first record</button>}</Empty>}
 <div className="tablefoot"><ShieldCheck size={15}/>{owner?'Only the owner can download the full dataset.':'You can view and edit only your own submissions.'}</div></section></TabsContent>
 <TabsContent value="entry"><div className="entry-layout"><section className="panel"><div className="panelhead"><div><h2>{editing?'Edit student record':'New student record'}</h2><p className="sub">Enter details carefully before submitting.</p></div><span className="classbadge">{editing?'EDIT':'NEW ENTRY'}</span></div><form className="entry-form" onSubmit={save}><div className="formgrid"><div><label htmlFor="student">Student name *</label><input id="student" required maxLength={150} autoComplete="off" placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><label htmlFor="school">School *</label><input id="school" required maxLength={200} autoComplete="off" placeholder="School name" value={form.school} onChange={e=>setForm({...form,school:e.target.value})}/></div><div><label htmlFor="father">Father’s number</label><input id="father" type="tel" maxLength={24} placeholder="Phone number" value={form.fatherPhone} onChange={e=>setForm({...form,fatherPhone:e.target.value})}/></div><div><label htmlFor="mother">Mother’s number</label><input id="mother" type="tel" maxLength={24} placeholder="Phone number" value={form.motherPhone} onChange={e=>setForm({...form,motherPhone:e.target.value})}/></div><div><label>Class *</label><Choice label="Select class" value={form.className} onChange={v=>setForm({...form,className:v})} items={classes}/></div></div><p className="sub">* Required. Add at least one parent’s number.</p><div className="formfooter"><span>Submitted as {email}</span><button className="primary" disabled={busy} type="submit">{busy?'Saving…':editing?'Save changes':'Submit record'} <ArrowUpRight size={17}/></button></div></form></section><aside className="entrynote"><span className="welcomeicon"><ShieldCheck size={25}/></span><h2>Ready for the owner</h2><p>Saved records are immediately available in the owner’s workspace.</p><hr/><b>Before you submit</b><p>Check the student’s spelling, school and class. Confirm the parent’s phone number.</p><p className="sub">You can return to your submissions to correct an entry. Edits reset its review status.</p></aside></div></TabsContent>
 {owner&&<TabsContent value="team"><section className="panel"><div className="panelhead"><div><h2>Intern access</h2><p className="sub">Create phone logins and set passwords for your interns.</p></div><button className="primary" onClick={()=>{setPerson({name:'',phone:'',password:''});setResetMode(false);setInvite(true)}}><Plus size={16}/> Add intern</button></div><div className="accessnote">Share the phone number and password with the intern privately. A password reset signs them out on all devices.</div>{data?.members.length?<Table><TableHeader><TableRow><TableHead>Intern</TableHead><TableHead>Mobile number</TableHead><TableHead>Access</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{data.members.map(m=><TableRow key={m.id}><TableCell>{m.name}</TableCell><TableCell>{m.phone}</TableCell><TableCell>{m.active?'Active':'Revoked'}</TableCell><TableCell><div className="actions"><button disabled={busy} onClick={()=>{setPerson({name:m.name,phone:m.phone,password:''});setResetMode(true);setInvite(true)}}>Reset password</button><button disabled={busy} onClick={()=>void action({action:'active',id:m.id,active:m.active?0:1},'/api/auth')}>{m.active?'Disable':'Enable'}</button></div></TableCell></TableRow>)}</TableBody></Table>:<Empty><EmptyHeader><EmptyTitle>No interns added yet</EmptyTitle><EmptyDescription>Add your first intern to allow them to submit student records.</EmptyDescription></EmptyHeader></Empty>}</section></TabsContent>}
 </Tabs></>}
 <footer>SRS Logics <span>Student records workspace</span></footer></main>
 <Dialog open={!!view} onOpenChange={open=>!open&&setView(null)}><DialogContent className="detaildialog"><DialogTitle>{view?.name}</DialogTitle><DialogDescription>Student record details</DialogDescription>{view&&<><dl className="details">{[['School',view.school],['Class',view.class_name],["Father’s number",view.father_phone||'Not provided'],["Mother’s number",view.mother_phone||'Not provided'],['Entered by',view.submitter_email],['Submitted',new Date(view.created_at).toLocaleString()],['Status',view.status]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="actions"><button onClick={()=>edit(view)}><PenLine size={16}/> Edit record</button>{owner&&<button className="primary" disabled={busy} onClick={async()=>{if(await action({action:'review',id:view.id,status:view.status==='Reviewed'?'New':'Reviewed'})){setView(null);toast.success('Review status updated.')}}}><Check size={16}/>{view.status==='Reviewed'?'Mark as new':'Mark reviewed'}</button>}</div></>}</DialogContent></Dialog>
 <Dialog open={invite} onOpenChange={setInvite}><DialogContent className="accountdialog"><DialogTitle>{resetMode?'Reset intern password':'Add intern'}</DialogTitle><DialogDescription>{resetMode?'Set a new password. Existing sessions will be signed out.':'The intern will log in using this mobile number and password.'}</DialogDescription><form onSubmit={async e=>{e.preventDefault();if(await action({action:'account',...person},'/api/auth')){setInvite(false);setPerson({name:'',phone:'',password:''});toast.success(resetMode?'Password reset.':'Intern account created.')}}}><label htmlFor="internname">Intern name</label><input id="internname" required maxLength={150} value={person.name} onChange={e=>setPerson({...person,name:e.target.value})}/><label htmlFor="internphone">Mobile number</label><input id="internphone" type="tel" required readOnly={resetMode} maxLength={16} placeholder="10-digit mobile number" value={person.phone} onChange={e=>setPerson({...person,phone:e.target.value})}/><label htmlFor="internpassword">{resetMode?'New password':'Set password'}</label><input id="internpassword" type="password" autoComplete="new-password" required minLength={10} maxLength={128} value={person.password} onChange={e=>setPerson({...person,password:e.target.value})}/><p className="sub">Use at least 10 characters. Passwords cannot be viewed after saving.</p><button className="primary mt-5" disabled={busy}>{busy?'Saving…':resetMode?'Reset password':'Create account'}</button></form></DialogContent></Dialog>
 <Dialog open={ownerPassword} onOpenChange={setOwnerPassword}><DialogContent className="accountdialog"><DialogTitle>Change owner password</DialogTitle><DialogDescription>Your other sessions will be signed out.</DialogDescription><form onSubmit={async e=>{e.preventDefault();if(await action({action:'password',...passwords},'/api/auth')){setOwnerPassword(false);setPasswords({currentPassword:'',password:''});toast.success('Owner password changed.')}}}><label htmlFor="currentpass">Current password</label><input id="currentpass" type="password" autoComplete="current-password" required value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/><label htmlFor="newpass">New password</label><input id="newpass" type="password" autoComplete="new-password" required minLength={10} maxLength={128} value={passwords.password} onChange={e=>setPasswords({...passwords,password:e.target.value})}/><button className="primary mt-5" disabled={busy}>Save password</button></form></DialogContent></Dialog>
 </div>
}
