import { getDb } from '../../../db';
import { requireOrigin } from '../../auth';
import { getSession } from '../../auth';
export const dynamic='force-dynamic';
const db=getDb;
function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
class Problem extends Error{constructor(message:string,public status=400){super(message)}}
async function identity(){const u=await getSession();if(!u)throw new Problem('Please sign in to continue.',401);return {...u,email:u.phone};}
function origin(req:Request){try{requireOrigin(req)}catch{throw new Problem('Request origin not allowed.',403)}}
const allowedClasses=['Nursery','LKG','UKG',...Array.from({length:12},(_,i)=>String(i+1)),'Other'];
function field(v:unknown,label:string,max=150){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new Problem(`${label} is required (maximum ${max} characters).`);return v.trim()}
function phone(v:unknown,label:string){const s=typeof v==='string'?v.trim():'';if(s && (!/^[+\d ()-]+$/.test(s)||s.replace(/\D/g,'').length<7||s.replace(/\D/g,'').length>15))throw new Problem(`Enter a valid ${label}.`);return s;}
function payload(v:any){const r={name:field(v.name,'Student name'),school:field(v.school,'School',200),fatherPhone:phone(v.fatherPhone,"father’s number"),motherPhone:phone(v.motherPhone,"mother’s number"),className:field(v.className,'Class',20)};if(!allowedClasses.includes(r.className))throw new Problem('Choose a valid class.');if(!r.fatherPhone&&!r.motherPhone)throw new Problem('Enter at least one parent’s phone number.');return r}
async function query(u:any,url:URL){let where=u.role==='owner'?'1=1':'submitter_id=?';const args:any[]=u.role==='owner'?[]:[u.userId];for(const [key,col] of [['class','class_name'],['status','status']] as const){const v=url.searchParams.get(key);if(v&&v!=='all'){where+=` AND ${col}=?`;args.push(v)}}const q=url.searchParams.get('q')?.trim();if(q){where+=' AND (name ILIKE ? OR school ILIKE ? OR father_phone ILIKE ? OR mother_phone ILIKE ?)';args.push(...Array(4).fill('%'+q+'%'))}const result=await db().prepare(`SELECT * FROM records WHERE ${where} ORDER BY created_at DESC`).bind(...args).all();return result.results}
export async function GET(req:Request){try{const u=await identity();const url=new URL(req.url);const records=await query(u,url);if(url.searchParams.get('export')==='csv'){if(u.role!=='owner')throw new Problem('Only the owner can download all records.',403);const cols=['name','school','father_phone','mother_phone','class_name','status','submitter_email','created_at'];const cell=(v:unknown)=>{let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'};const csv='\uFEFF'+[['Name','School',"Father’s number","Mother’s number",'Class','Status','Entered by','Submitted at'],...records.map((r:any)=>cols.map(k=>r[k]))].map(row=>row.map(cell).join(',')).join('\r\n');return new Response(csv,{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="student-records.csv"','Cache-Control':'no-store'}})}const members=u.role==='owner'?(await db().prepare("SELECT id,phone,name,active FROM auth_accounts WHERE role='intern' ORDER BY name").all()).results:[];return json({user:u,records,members})}catch(e){return fail(e)}}
export async function POST(req:Request){try{origin(req);if(Number(req.headers.get('content-length')||0)>16000)throw new Problem('Request too large.');const u=await identity();const v:any=await req.json();if(v.action==='review'){if(u.role!=='owner')throw new Problem('Owner access required.',403);if(!['New','Reviewed'].includes(v.status))throw new Problem('Invalid status.');await db().prepare('UPDATE records SET status=?,updated_at=? WHERE id=?').bind(v.status,new Date().toISOString(),field(v.id,'Record ID')).run();return json({ok:true})}if(v.action!=='save')throw new Problem('Unknown action.');const r=payload(v);const id=field(v.id,'Record ID');if(!/^[a-f\d-]{36}$/.test(id))throw new Problem('Invalid record ID.');const old=await db().prepare('SELECT * FROM records WHERE id=?').bind(id).first<any>();if(old){if(old.submitter_id!==u.userId&&u.role!=='owner')throw new Problem('You can only edit your own records.',403);await db().prepare('UPDATE records SET name=?,school=?,father_phone=?,mother_phone=?,class_name=?,status=?,updated_at=? WHERE id=?').bind(r.name,r.school,r.fatherPhone,r.motherPhone,r.className,'New',new Date().toISOString(),id).run()}else{const now=new Date().toISOString();await db().batch([db().prepare('INSERT INTO records (id,name,school,father_phone,mother_phone,class_name,submitter_id,submitter_email,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(id,r.name,r.school,r.fatherPhone,r.motherPhone,r.className,u.userId,u.email,'New',now,now),db().prepare('UPDATE members SET user_id=? WHERE email=? AND user_id IS NULL').bind(u.userId,u.email.toLowerCase())])}return json({ok:true,id})}catch(e){return fail(e)}}
function fail(e:unknown){if(e instanceof Problem)return json({error:e.message},e.status);if(e instanceof SyntaxError)return json({error:'Invalid request.'},400);console.error('Workspace operation failed',e);return json({error:'We could not reach your records. Please try again; your form has been kept.'},503)}
